config/routes.rb
Rails.application.routes.draw do
  devise_for :personas
  devise_for :empresas
  root "ofertas#index"
  resources :ofertas do
    collection do
      get "search"
      get "postuladas"
    end
    resources :empresa, only: [:new, :create]
  end  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  has_and_belongs_to_many :oferta, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/modalidad.rb
class Modalidad < ApplicationRecord
end

app/models/oferta.rb
class Oferta < ApplicationRecord
end

app/models/persona.rb
class Persona < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/postulacion.rb
class Postulacion < ApplicationRecord
  belongs_to :persona
  belongs_to :oferta
end

app/models/region.rb
class Region < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:representante])
  end
end

app/controllers/ofertas_controller.rb
class OfertasController < ApplicationController
  before_action :authenticate_empresa!, except: %i[index show search postuladas]
  before_action :set_oferta, only: %i[ show edit update destroy ]

  # GET /ofertas or /ofertas.json
  def index
    @ofertas = Oferta.order(:cargo).page(params[:page]).per(4)
  end

  # GET /ofertas/1 or /ofertas/1.json
  def show
  end

  # GET /ofertas/new
  def new
    @oferta = Oferta.new
  end
  
  def postuladas
    @postula = Oferta.find_by("cargo LIKE ?", "%#{params[:query]}%")
  end

  def search
    @search = Oferta.find_by("cargo LIKE ?", "%#{params[:query]}%")
  end

  # GET /ofertas/1/edit
  def edit
  end

  # POST /ofertas or /ofertas.json
  def create
    @oferta = Oferta.new(oferta_params)

    respond_to do |format|
      if @oferta.save
        format.html { redirect_to oferta_url(@oferta), notice: "Oferta was successfully created." }
        format.json { render :show, status: :created, location: @oferta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oferta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ofertas/1 or /ofertas/1.json
  def update
    respond_to do |format|
      if @oferta.update(oferta_params)
        format.html { redirect_to oferta_url(@oferta), notice: "Oferta was successfully updated." }
        format.json { render :show, status: :ok, location: @oferta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oferta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ofertas/1 or /ofertas/1.json
  def destroy
    @oferta.destroy

    respond_to do |format|
      format.html { redirect_to ofertas_url, notice: "Oferta was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_oferta
    @oferta = Oferta.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def oferta_params
    params.require(:oferta).permit(:cargo, :descripcion, :cant_vacantes, :salario_min, :salario_max, :fecha_inicio, :modalidad, :region_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oferta_helper.rb
module OfertaHelper
end

app/helpers/ofertas_helper.rb
module OfertasHelper
end

app/views/empresas/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/empresas/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-outline-dark" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OfertaLaboral</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if empresa_signed_in? %>
            <div>
                <p>Bienvenid@ <%= current_empresa.representante.upcase %> de <%= current_empresa.razon_social.upcase %>!!</p>
                
                <%= link_to "Inicio", root_path, class: "btn btn-outline-dark" %> 
                <%= link_to "Buscar Ofertas Creadas", search_ofertas_path, class: "btn btn-outline-dark" %>
                <%= link_to "Cerrar Sesión", destroy_empresa_session_path, method: :delete, class: "btn btn-outline-dark" %>
            </div>
        <% elsif persona_signed_in? %>
            <div>
                <%= link_to "Inicio", root_path, class: "btn btn-outline-dark" %>
                <%= link_to "Perfil", edit_persona_registration_path, class: "btn btn-outline-dark" %>
                <%= link_to "Mis Postulaciones", postuladas_ofertas_path, class: "btn btn-outline-dark" %> 
                <%= link_to "Cerrar Sesión", destroy_persona_session_path, method: :delete, class: "btn btn-outline-dark" %>
            </div>
        <% else %>
        <div>
                <%= link_to "Inicio", root_path, class: "btn btn-outline-dark" %>
                <%= link_to "Registar Empresa", new_empresa_registration_path, class: "btn btn-outline-dark" %> 
                <%= link_to "Registar Persona", new_persona_registration_path, class: "btn btn-outline-dark" %> 
                <%= link_to "Login Empresa", new_empresa_session_path, class: "btn btn-outline-dark" %>
                <%= link_to "Login Persona", new_persona_session_path, class: "btn btn-outline-dark" %>
                <%= link_to "Buscar", search_ofertas_path, class: "btn btn-outline-dark" %>
            </div>
        <% end %>
    <%= yield %>
	<div id="reservado"><br>&copy; Todos los Derechos Reservados • 2022 • Joselis Briceño</div>
  </body>
</html>

app/views/ofertas/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">

<%= form_with(model: oferta) do |form| %>
  <% if oferta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oferta.errors.count, "error") %> prohibited this oferta from being saved:</h2>

      <ul>
        <% oferta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

        <br>
        <div class="field">
          <%= form.label :cargo %>
          <%= form.text_field :cargo %>
        </div>
        <br>

        <div class="field">
          <%= form.label :descripción %>
          <%= form.text_area :descripcion, :rows=>2, :cols=>50  %>
        </div>
        <br>

        <div class="field">
          <%= form.label :Vacantes %>
          <%= form.number_field :cant_vacantes %>
        </div>
        <br>

        <div class="field">
          <%= form.label :salario_mínimo %>
          <%= form.number_field :salario_min %>
        </div>
        <br>

        <div class="field">
          <%= form.label :salario_máximo %>
          <%= form.number_field :salario_max %>
        </div>
        <br>

        <div class="field">
          <%= form.label :fecha_inicio %>
          <%= form.datetime_select :fecha_inicio %>
        </div>
        <br>

        <div class="field">
          <%= form.label :modalidad_trabajo %>
          <%= collection_select(:ofertas, :modalidad_trabajo, Modalidad.all, :nombre, :nombre, prompt: true) %>
        </div>
        <br>

        <div class="field">
          <%= form.label :región %>
          <%= collection_select(:ofertas, :region_id, Region.all, :id, :nombre, prompt: true) %>
        </div>
        <br>


        <div class="actions">
          <%= form.submit %>
        </div>
<% end %>

        </div>
    </div>
</div>

app/views/ofertas/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
        <br>
        <h1>Editando Oferta: <%= @oferta.cargo.upcase %></h1>

        <%= render "form", oferta: @oferta %>
        <br>
        <%= link_to "Ver", @oferta, class: "btn btn-outline-dark" %> 
        <%= link_to "Volver", ofertas_path, class: "btn btn-outline-dark" %>
        </div>
    </div>
</div>

app/views/ofertas/index.html.erb
<br><h1 class="ofer">Ofertas Laborales</h1><br>

<table class="table table-hover">
  <thead>
    <tr>
      <th>CARGO</th>
      <th>DESCRIPCIÓN</th>
      <th>VACANTES</th>
      <th>RANGO DE SALARIO</th>
      <th>FECHA DE INICIO</th>
      <th>MODALIDAD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ofertas.each do |oferta| %>
      <tr>
        <td><%= oferta.cargo %></td>
        <td><%= oferta.descripcion %></td>
        <td><%= oferta.cant_vacantes %></td>
        <td>Entre $<%= oferta.salario_min %> a $<%= oferta.salario_max %> CLP.</td>
        <td><%= oferta.fecha_inicio %></td>
        <td><%= oferta.modalidad_trabajo %></td>
        <% if empresa_signed_in? %>
        <td><%= link_to "Ver", oferta, class: "btn btn-outline-dark" %></td>
        <td><%= link_to "Editar", edit_oferta_path(oferta), class: "btn btn-outline-dark" %></td>
        <td><%= link_to "Eliminar", oferta, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-outline-dark" %></td>
        <% else %>
		<td><%= link_to "Ver", oferta, class: "btn btn-outline-dark" %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @ofertas %>
<br>
<% if empresa_signed_in? %>
<%= link_to "Nueva Oferta", new_oferta_path, class: "btn btn-outline-dark" %>
<% end %>
<%= link_to "Volver", :back, class: "btn btn-outline-dark" %>

app/views/ofertas/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
<br>
<h1>Nueva Oferta Laboral</h1>
<br>
<%= render "form", oferta: @oferta %>

<%= link_to "Volver", ofertas_path, class: "btn btn-outline-dark" %>
        </div>
    </div>
</div>

app/views/ofertas/postuladas.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
<br>
  <%= form_with url: "/ofertas/postula", method: :get do |form| %>
        <%= form.label :query, "Buscar Mis Postulaciones:" %>
        <%= form.text_field :query %>
        <%= form.submit "Buscar" %>
    <% end %>

    <% if @postula %>

    <p>
        <strong>Cargo:</strong>
        <%= @postula.cargo %>
    </p>

    <p>
        <strong>Descripción:</strong>
        <%= @postula.descripcion %>
    </p>

    <p>
        <strong>Vacantes:</strong>
        <%= @postula.cant_vacantes %>
    </p>

    <p>
        <strong>Salario:</strong>
        Entre $<%= @postula.salario_min %> a $<%= @postula.salario_max %> CLP.
    </p>

    <p>
        <strong>Fecha de Inicio:</strong>
        <%= @postula.fecha_inicio %>
    </p>
    <% else %>
    <%= "***Ningun dato encontrado***" %>
    <% end %>

    <%= link_to "Volver", ofertas_path, class: "btn btn-outline-dark" %>

        </div>
    </div>
</div>

app/views/ofertas/search.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
<br>
  <%= form_with url: "/ofertas/search", method: :get do |form| %>
        <%= form.label :query, "Buscar Ofertas Laborales:" %>
        <%= form.text_field :query %>
        <%= form.submit "Buscar" %>
    <% end %>

    <% if @search %>

    <p>
        <strong>Cargo:</strong>
        <%= @search.cargo %>
    </p>

    <p>
        <strong>Descripción:</strong>
        <%= @search.descripcion %>
    </p>

    <p>
        <strong>Vacantes:</strong>
        <%= @search.cant_vacantes %>
    </p>

    <p>
        <strong>Salario:</strong>
        Entre $<%= @search.salario_min %> a $<%= @search.salario_max %> CLP.
    </p>

    <p>
        <strong>Fecha de Inicio:</strong>
        <%= @search.fecha_inicio %>
    </p>
    <% else %>
    <%= "***Ningun dato encontrado***" %>
    <% end %>

    <%= link_to "Volver", ofertas_path, class: "btn btn-outline-dark" %>

        </div>
    </div>
</div>

app/views/ofertas/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">

          <p id="notice"><%= notice %></p>

          <h2>CARGO DE: <%= @oferta.cargo.upcase %> </h2>
          <br>

          <p>
            <strong>Descripcion:</strong>
            <%= @oferta.descripcion %>
          </p>

          <p>
            <strong>Cant vacantes:</strong>
            <%= @oferta.cant_vacantes %>
          </p>

          <p>
            <strong>Salario min:</strong>
            <%= @oferta.salario_min %>
          </p>

          <p>
            <strong>Salario max:</strong>
            <%= @oferta.salario_max %>
          </p>

          <p>
            <strong>Fecha inicio:</strong>
            <%= @oferta.fecha_inicio %>
          </p>

          <p>
            <strong>Modalidad:</strong>
            <%= @oferta.modalidad_trabajo %>
          </p>
          <% if empresa_signed_in? %> 
              <%= link_to "Editar", edit_oferta_path(@oferta), class: "btn btn-outline-dark" %>
            
          <% end %> 
              <% if persona_signed_in? %> 
              <%= link_to "Postular", "javascript:(alert('Postulado Satisfactoriamente'))", class: "btn btn-outline-dark" %>
            
          <% end %> 
          <%= link_to "Volver", ofertas_path, class: "btn btn-outline-dark" %>

        </div>
    </div>
</div>

app/views/personas/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/personas/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-outline-dark" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>